### PR TITLE
Improve rational quadratic spline implementation

### PR DESCRIPTION
**Pull request by oschulz**

### CODE REVIEW

**Comment by oschulz** [comment]
CC @Micki-D @LolianSh

**Comment by oschulz** [comment]
@Micki-D is this part of PR  #4, or do we merge it before?

**Comment by Micki-D** [comment]
No, I would only merge PR #4, and discard this PR #2.

**Comment by oschulz** [comment]
Ah, #4 merges into this one. So we'd merge #4 and then #2.

**Comment by Micki-D** [comment]
Oh I see, yes then let's do that.

**Comment by Micki-D** [comment]
Should I go ahead and merge #4 ?

**Comment by oschulz** [comment]
> Should I go ahead and merge #4

Sure! Afterwards you can continue to push directly to the dev branch in the main repo, those commits will end up here on #2 then.

**Comment by Micki-D** [comment]
Alright!

**Comment by Micki-D** [comment]
So I disabled the Aqua.jl piracy tests, as that caused an error, and from the Aqua documentation, I gather they are still somewhat experimental.

**Comment by oschulz** [comment]
Also try using JET.jl and run `JET.report_package(MonotonicSplines)`. Sometimes it repots things that may actually be Ok, but mosty it reports stuff one should definitely fix.

**Comment by Micki-D** [comment]
Alright, I did that and I found issues with the function we use to shift things from the CPU to the GPU and back. I used to use "gpu()" from Flux.jl. I think I could also use "cu()" from CUDA.jl 

Which should I choose, or what would be a better alternative?

**Comment by oschulz** [comment]
> Which should I choose, or what would be a better alternative?

Use `Adapt.adapt` and/or our new https://github.com/oschulz/HeterogeneousComputing.jl

**Comment by Micki-D** [comment]
That is a nice packagel! I overloaded some of the `KernelAbstractions.jl` API so that it works with the `HeterogeneousComputing` types and adapted the splines code to use it together with `Adapt.adapt()` for the management of the computing device
I also checked again with `JET`, and it didn't complain

The tests all pass, but they all work with the CPU and I haven't yet tested the execution on a GPU

Is there a way to do that in the tests?

**Comment by oschulz** [comment]
> Is there a way to do that in the tests?

We can't run CPU tests on GitHub Actions - we could set up a custom system, but that would be more involved. You should run local GPU tests, though. You can use something like this

```julia
    isdefined(Main, :CUDA)
        ... run tests on CUDA ...
    end
```

in the test code. Then one can easily run local GPU test with

```julia
import CUDA
include("test/runtests.jl")
```

**Comment by Micki-D** [comment]
I see. Alright I'll get on that!

**Comment by Micki-D** [comment]
I added tests for the GPU by doing 
`compute_units = isdefined(Main, :CUDA) ? [AbstractComputeUnit(CUDA.device()), CPUnit()] : [CPUnit()]`
And then iterating the tests over `compute_units`, using `adapt()` to put the regarded objects on the currently selected compute unit.

The CPU tests work, but I had trouble getting all the appropriate package versions working together to run the GPU tests.

**Comment by oschulz** [comment]
> but I had trouble getting all the appropriate package versions working together to run the GPU tests.

For CUDA at least, there shouldn't be version problems, really.

**Comment by Micki-D** [comment]
Well, for `HeterogeneousComputing` to work with `KernelAbstractions`, `CUDA` >= 4.0 is required but that in turn requires some other packages like `GPUArrays` to be at certain versions.
I loaded some Packages directly from their respective Github repos to obtain versions that aren't accessible with julia >=1.8 but I didn't manage to satisfy all the requirements

Did I do something wrong?

**Comment by oschulz** [comment]
You shouldn't need  dev Branches of those packages. Do you have CUDAKernels installed? That's deprecated, remove it.

**Comment by Micki-D** [comment]
I don't have `CUDAKernels` but I'll keep trying, maybe I did something wrong

**Comment by oschulz** [comment]
It should just work:

```
(@v1.9) pkg> activate --temp
  Activating new project at `/tmp/jl_QGdjQO`

(jl_QGdjQO) pkg> add KernelAbstractions, GPUArrays, CUDA
   Resolving package versions...
    Updating `/tmp/jl_QGdjQO/Project.toml`
  [052768ef] + CUDA v4.4.0
  [0c68f7d7] + GPUArrays v8.8.1
  [63c18a36] + KernelAbstractions v0.9.6
  
  
 (@v1.6) pkg> activate --temp
  Activating new environment at `/tmp/jl_nZb4eN/Project.toml`

(jl_nZb4eN) pkg> add KernelAbstractions, GPUArrays, CUDA
   Resolving package versions...
    Updating `/tmp/jl_nZb4eN/Project.toml`
  [052768ef] + CUDA v4.4.0
  [0c68f7d7] + GPUArrays v8.8.1
  [63c18a36] + KernelAbstractions v0.9.6
```

We should definitely stay Julia v1.6-compatible for now, but that shouldn't be a problem.
I

**Comment by Micki-D** [comment]
I implemented the changes we discussed. 
I initiate the arrays for the gradients as `fill!(similar(x),zero(eltype(x)))` since only few entries are actually mutated by the kernels, so initializing the arrays as `undef` may lead to errors.

**Comment by oschulz** [comment]
Thanks @Micki-D !

**Comment by oschulz** [comment]
https://github.com/JuliaRegistries/General/pull/87627

**Pull request merged**
