### PR TITLE
Add test_utils.jl

### PR DESCRIPTION
**Pull request by Micki-D**
Add docstrings and tests.
The test outputs stored in txt files and are loaded during testing, using DelimitedFiles.

### CODE REVIEW

**Comment by oschulz** [comment]
We should avoid keeping binary files (JLD2) in the repo. How many numbers do we need here as a reference? Can we only use a few and then use a (small) text file?

**Comment by Micki-D** [comment]
There aren't so many numbers, just 100-200. I'll put them in a text file

**Comment by Micki-D** [comment]
It seems the environment for the tests is missing the "Test" package. Is that something I can fix?

**Comment by oschulz** [comment]
> It seems the environment for the tests is missing the "Test" package. Is that something I can fix?

There shouldn't be a Manifest.toml under "test", and "test/Project.toml" (https://github.com/bat/MonotonicSplines.jl/blob/dev/test/Project.toml) is missing from the PR

**Comment by Micki-D** [comment]
Aah, I see, I deleted that. Thank you!

**Comment by Micki-D** [comment]
I think the failing tests might be due to numerical imprecision. I'll exchange the "=="'s to "isapprox"s. I'll update this tomorrow

**Comment by oschulz** [comment]
> I'll update this tomorrow

Thanks! Yes, use `isapprox` in general, except where you would actually excpect bitwise equality.

**Comment by Micki-D** [comment]
Alright, so the lines that are yet un-covered according to Codecov are the declarations of the thread-local indexes in the kernels and the ChainrulesCore.rrule() for the forward spline kernel. 

The latter doesn't give an output, so I didn't know how I should test that explicitly, but I figure this rrule determines the gradients, and thus by checking the gradients, the rrule gets tested indirectly.

I tried to increase the threadcount to also hit the local index declarations in the kernels, but Codecov still says they are not covered,  so perhaps they are only evaluated on the GPU?

**Pull request merged**
